Added new listTypes normalnotpublishable and latenotpublishable used …
IMIO/Products.MeetingCommunes pull request #23
Opened 2021-04-15 13:37 UTC by odelaere

…in portal

2021-04-15 13:53 UTC, gbastien requested changes
@odelaere qq détails...

2021-04-15 13:53 UTC, gbastien commented on src/Products/MeetingCommunes/Extensions/add_portal_configuration.py
> +    meeting_config.listTypes = new_listTypes
@odelaere attention d'utiliser accessor et mutator avec AT, donc getListTypes et setListTypes

2021-04-15 13:53 UTC, gbastien commented on src/Products/MeetingCommunes/locales/fr/LC_MESSAGES/PloneMeeting.po
> +msgstr "En retard (Non publiable)"
Par défaut la traduction dans PM est "Point supplémentaire" autant reprendre cette traduction "Point supplémentaire (Non publiable)"

2021-04-15 13:53 UTC, gbastien commented on src/Products/MeetingCommunes/locales/fr/LC_MESSAGES/PloneMeeting.po
> +msgstr "Normal (Non publiable)"
Me chose par défaut c'est "Point normal", çà donnerait "Point normal (Non publiable)"

2021-04-15 15:02 UTC, odelaere commented on src/Products/MeetingCommunes/locales/fr/LC_MESSAGES/PloneMeeting.po
> +msgstr "En retard (Non publiable)"
je m'était basé là dessus en fait https://github.com/IMIO/imio.pm.locales/blob/9e577eb4b0a9b17b36d546c356b48524d06c4373/src/imio/pm/locales/locales/fr/LC_MESSAGES/PloneMeeting.po#L4301

2021-04-15 15:05 UTC, odelaere commented on src/Products/MeetingCommunes/locales/fr/LC_MESSAGES/PloneMeeting.po
> +msgstr "En retard (Non publiable)"
Du coup faudrait p-e corriger là bas aussi. Ou alors il manque un truc ici

2021-04-16 07:02 UTC, gbastien approved these changes
Je n'ai pas testé, mais le code me semble ok

2021-04-16 09:00 UTC, merged