Improved print_all_annexes #SUP-19228
IMIO/Products.MeetingCommunes pull request #27
Opened 2021-06-29 10:05 UTC by odelaere

2021-06-29 10:15 UTC, gbastien requested changes
@odelaere 

est ce que tu pourrais ajouter une ligne dans le changelog (même si conflict lors du cherry pick) et ajouter un test qui teste au moins l'ensemble des paramètres?

Merci!

2021-06-29 10:15 UTC, gbastien commented on src/Products/MeetingCommunes/browser/overrides.py
> +    def print_all_annexes(self, portal_types=['annex'], excludes={}, include_icon=False, long_format=False):
J'utiliserais "filters" au lieu de "excludes", c'est plus compréhensible que de dire ce qu'on ne veut pas?
Je veux les annexes publiables, plutôt que je ne veux pas les annexes non publiables.

2021-06-29 10:15 UTC, gbastien commented on src/Products/MeetingCommunes/browser/overrides.py
> +            mime_type = self.portal.mimetypes_registry.lookup(annex.file.contentType)[0]
définir une fois mimetypes en dehors de la fonction, aller chercher par chemin fait des checks d'accès notamment

2021-06-29 10:15 UTC, gbastien commented on src/Products/MeetingCommunes/browser/overrides.py
> +            extension = annex.file.filename.split(u'.')[-1]
dans certains rares cas filename peut être None...

2021-06-29 10:18 UTC, odelaere commented on src/Products/MeetingCommunes/browser/overrides.py
> +            extension = annex.file.filename.split(u'.')[-1]
uh! wtf?

2021-06-30 13:52 UTC, gbastien requested changes
@odelaere 
- dire dans changelog où est print_all_annexes
- ajouter un test pour filters (ne fonctionne pas pour l'instant)
- ordre des imports
- long_format sur 2 lignes?

Merci!

2021-06-30 13:52 UTC, gbastien commented on src/Products/MeetingCommunes/browser/overrides.py
> +import cgi
Import à déplacer sous les autres

2021-06-30 13:52 UTC, gbastien commented on src/Products/MeetingCommunes/browser/overrides.py
> +            if long_format:
Est ce qu'en long_format on ne passerait pas à la ligne comme c'est fait pour le doc publications actuel?  Ça peut avoir + de sens car du coup la ligne est plus longue...  Si c'est juste un petit "[pdf]" à côté çà me semble ok sur une ligne, mais en full, sur 2 lignes c'est mieux il me semble... ou alors permettre de passer un pattern mais çà commence à faire bcp...

2021-06-30 13:52 UTC, gbastien commented on src/Products/MeetingCommunes/tests/testCustomViews.py
Ajouter un test avec "filters", l'idée est que cette méthode soit utilisée dans le document "Publications" qui filtre sur les éléments "publiables".  Actuellement passer des filters ne change rien, d'où test plus qu'utile ;-)

2021-07-02 07:10 UTC, gbastien commented on src/Products/MeetingCommunes/browser/overrides.py
> +                for attribute in filters:
@odelaere je préfère la notation "for attribute, value in filters.items(): ..." et réutiliser "value" au lieu de ré-accéder le dict via "filter[attribute]" plus lisible à mon avis...

2021-07-02 09:16 UTC, gbastien commented on src/Products/MeetingCommunes/browser/overrides.py
> +                for attribute, value in filters:
@odelaere filters.items(), par défaut çà appelle "keys"

2021-07-02 11:57 UTC, gbastien commented
LGTM

2021-07-02 12:10 UTC, merged